name: Build C Wrapper v0.2.0

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git build-essential
          sudo apt-get install -y libgtk-3-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd wrapper
          make

      - name: Insert version into README (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd wrapper
          sed -i "s/{{VERSION}}/${{ github.ref_name }}/g" README.md

      - name: Package final zip for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p dist
          cp wrapper/launcher dist/
          cp wrapper/README.md dist/
          cd dist
          zip -r ../Game-${{ github.ref_name }}-linux.zip .
          cd ..

      - name: Upload to GitHub Release (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: Game-${{ github.ref_name }}-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
