name: Linter (PyLint)

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Run Pylint and extract score
        run: |
          SCORE=$(pylint data | grep "Your code has been rated at" | sed -E 's/.* ([0-9\.]+)\/10.*/\1/')
          echo "Pylint score: $SCORE"
          mkdir -p badge
          echo "{\"schemaVersion\":1,\"label\":\"pylint\",\"message\":\"$SCORE/10\",\"color\":\"blue\"}" > badge/pylint-badge.json

      - name: Upload badge to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badge
