name: Linter

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint data > pylint-report.txt || true
          grep "Your code has been rated at" pylint-report.txt > pylint-score.txt || true

      - name: Upload Pylint report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-score
          path: pylint-score.txt