name: Build C Wrapper v0.0.8

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd wrapper
          gcc launcher.c -o launcher

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd wrapper
          gcc launcher.c -o launcher.exe

      - name: Upload to GitHub Release (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: wrapper/launcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: wrapper/launcher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}