name: Build C Wrapper v0.0.3

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set file extension
        id: vars
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "EXT=.exe" >> $GITHUB_ENV
          else
            echo "EXT=" >> $GITHUB_ENV
          fi

      - name: Build C wrapper
        run: |
          cd wrapper
          gcc launcher.c -o launcher$EXT

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wrapper/launcher${{ env.EXT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
