name: Python Tests

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # if you don't have a file, it's safe

    - name: Run unittests
      run: |
        PYTHONPATH=. python3 -m unittest discover -s tests
    
    - name: Run tests with coverage
      run: |
        pip install coverage
        PYTHONPATH=. coverage run --rcfile=.coveragerc --source=data -m unittest discover -s tests
        coverage xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml